spring:
  datasource:
    url: jdbc:mysql://localhost/swagalls
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  messages:
    basename: i18n/messages,messages
